apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pod-access-devices-scc
allowPrivilegeEscalation: false
defaultAddCapabilities: []
requiredDropCapabilities:
  - ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - docker/default
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
readOnlyRootFilesystem: false
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:homelab-hub:hub-gitops-argocd-application-controller