kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: hostdevice-scc
namespace: octoprint
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false