apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: octoprint
    app.kubernetes.io/instance: octoprint
    app.kubernetes.io/component: octoprint
    app.kubernetes.io/part-of: octoprint
  name: octoprint
spec:
  tls:
    termination: edge
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: octoprint-svc
    weight: 100
  wildcardPolicy: None
