apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: octoprint
  name: octoprint
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: octoprint-svc
    weight: 100
  wildcardPolicy: None
