apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoprint
  namepace: octoprint
  labels:
    application: octoprint
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: octoprint
      app.kubernetes.io/part-of: octoprint
  template:
    metadata:
      labels:
        app.kubernetes.io/name: octoprint
        app.kubernetes.io/instance: octoprint
        app.kubernetes.io/component: octoprint
        app.kubernetes.io/part-of: octoprint
      name: octoprint
    spec:
      containers:
      - name: octoprint
        image: octoprint/octoprint:minimal
        ports:
        - containerPort: 5000
        securityContextConstraints:  # Apply the SCC here
          name: pod-access-devices-scc
        resources:
          requests:
            memory: 2000Mi
            cpu: '1'
          limits:
            memory: 3500Mi
            cpu: '2'
        volumeMounts:
          # - mountPath: /octoprint
          #   name: octoprint
          #   readOnly: false
          - mountPath: /dev/ttyACM0
            name: ttyacm0
            readOnly: false
      volumes:
      # - name: octoprint
      #   persistentVolumeClaim:
      #     claimName: octoprint
      - name: ttyacm0
        hostPath:
          path: /dev/ttyACM0