apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint
  labels:
    app: octoprint
  namespace: octoprint
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi