apiVersion: v2
description: A helm chart to provision minio and nfs storage (which it will user)
keywords:
- pattern
name: minio
version: 0.0.1
dependencies:
  - name: nfs-subdir-external-provisioner
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    version: "4.0.2"
