---
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

minio:
  key: secret/data/global/minio

csi-driver-nfs:
  controller:
    runOnControlPlane: true
  externalSnapshotter:
    enabled: true
    customResourceDefinitions:
      enabled: true


## Run this
# oc adm policy add-scc-to-user privileged -z csi-nfs-node-sa -n minio
# oc adm policy add-scc-to-user privileged -z csi-nfs-controller-sa -n minio


