---
global:
  hubClusterDomain: hub.example.com
  localCluster: local.example.com


csi-driver-nfs:
  controller:
    runOnControlPlane: true
  externalSnapshotter:
    enabled: true
    customResourceDefinitions:
      enabled: true


## Run this
# oc adm policy add-scc-to-user privileged -z csi-nfs-node-sa -n csi-driver-nfs
# oc adm policy add-scc-to-user privileged -z csi-nfs-controller-sa -n csi-driver-nfs


