apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: 'worker'
  name: disable-ipv6
spec:
  config:
    ignition:
      version: 3.3.0
    storage:
      files:
      - path: /etc/sysctl.d/99-disable-ipv6.conf
        mode: 0644
        overwrite: true
        contents:
          inline: |
            net.ipv6.conf.all.disable_ipv6=1
