---
global:
  pattern: homelab
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

# Leaving as hub as there are lots of presumptions
main:
  clusterGroupName: hub
