clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
  - open-cluster-management
  - vault
  - golang-external-secrets
  - octoprint
  - homeassistant
  - cert-manager
  - tailscale

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.8
      #csv: advanced-cluster-management.v2.6.1
    # certmanager:
    #   name: cert-manager
    #   namespace: cert-manager
    #   channel: stable

  projects:
  - hub
  - octoprint
  - config-demo
  - hello-world
  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
        - /spec/loggingCA

    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    octoprint:
      name: octoprint
      namespace: octoprint
      project: octoprint
      path: charts/all/octoprin

    tailscale:
      name: tailscale
      namespace: tailscale
      project: hub
      path: charts/all/tailscale


  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
    - name: hello-world
      # ansible playbook to be run
      playbook: common/ansible/playbooks/hello-world/hello-world.yaml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"

  managedClusterGroups:
    exampleRegion:
      name: group-one
      acmlabels:
      - name: clusterGroup
        value: group-one
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false
