apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: homeassistant
  name: homeassistant
spec:
  dataVolumeTemplates:
  - metadata:
      name: homeassistant-dv 
    spec:
      storage:
        resources:
          requests:
            storage: 80Gi 
        storageClassName: lvms-vg1
      source:
        http:
          url: "https://github.com/home-assistant/operating-system/releases/download/{{ .Values.homeassistant.version }}/haos_generic-x86-64-{{ .Values.homeassistant.version }}.img.xz"
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: homeassistant
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: homeassistant-disk-1
          # - disk:
          #     bus: virtio
          #   name: cloudinitdisk
          interfaces:
            - bridge: {}
              macAddress: '02:ec:14:00:02:0f'
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        memory:
          guest: 4Gi
      networks:
        - multus:
            networkName: homeassistant/localnet
          name: default
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: homeassistant-dv
        name: homeassistant-disk-1
      # - cloudInitNoCloud:
      #     secretRef:
      #       name: userdata
      #   name: cloudinitdisk