secretStore:
  name: vault-backend
  kind: ClusterSecretStore

sshpubkey:
  key: secret/data/global/sshpubkey

userdata:
  key: secret/data/global/cloudinit-userdata

homeassistant:
  name: homeassistant
  version: "13.1"


## Run this
# oc adm policy add-scc-to-user privileged -z csi-nfs-node-sa -n minio
# oc adm policy add-scc-to-user privileged -z csi-nfs-controller-sa -n minio


