---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: logging-loki-s3-esc
  namespace: openshift-logging
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: logging-loki-s3 
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.loki_esc.key }}
