---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: minio-esc
  namespace: minio
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: minio-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.minio.key }}
