# apiVersion: k8s.cni.cncf.io/v1beta1
# kind: MultiNetworkPolicy
# metadata:
#   name: allow-ssh-inbound
#   namespace: default
#   annotations:
#     k8s.v1.cni.cncf.io/policy-for: default/localnet
# spec:
#   podSelector:
#     matchLabels:
#       app: centos7-salmon
#   policyTypes:
#   - Ingress
#   ingress:
#   - ports:
#     - protocol: TCP
#       port: 22

---
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: allow-ssh
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/policy-for: default/localnet
spec:
  podSelector:
    matchLabels:
      app: centos7-salmon
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.2.2/32
    ports:
    - protocol: TCP
      port: 22
#   egress:
#   - to:
#     - ipBlock:
#         cidr: 192.168.200.1/32
#     ports:
#     - protocol: TCP
#       port: 5432
---