apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: allow-ssh-inbound-2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/policy-for: default/localnet
spec:
  podSelector:
    matchLabels:
      app: centos7-salmon-blackbird-20
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 22