# apiVersion: nmstate.io/v1
# kind: NodeNetworkConfigurationPolicy
# metadata:
#   name: br0 
# spec:
#   nodeSelector:
#     node-role.kubernetes.io/worker: '' 
#   desiredState:
#     interfaces:
#       - bridge:
#           options:
#             stp:
#               enabled: true
#           port:
#           - name: eno1
#         ipv4:
#           dhcp: true
#           enabled: true
#         ipv6:
#           dhcp: true
#           enabled: true
#         name: br0
#         state: up
#         type: linux-bridge