apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: mapping 
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: '' 
  desiredState:
    ovn:
      bridge-mappings:
      - localnet: localnet01
        bridge: br-ex 
        state: present
      - localnet: tailscale
        bridge: br-ex
        state: present
      - localnet: homeasstant
        bridge: br-ex
        state: present