---
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: outbound-allow
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/policy-for: default/localnet
spec:
  podSelector: {}
#   policyTypes:
#   - Ingress
#   podSelector:
#     matchLabels:
#       app: centos7-salmon
  policyTypes:
  - Egress
  egress:
  - {}