apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: tailscale
  annotations:
    serviceaccounts.openshift.io/scc: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxies
  namespace: tailscale
  annotations:
    serviceaccounts.openshift.io/scc: privileged