---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: sshpubkey-esc
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: sshpubkey
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.sshpubkey.key }}
