apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet 
  namespace: tailscale
spec:
  config: |2
    {
            "cniVersion": "0.3.1", 
            "name": "tailscale", 
            "type": "ovn-k8s-cni-overlay", 
            "topology": "localnet", 
            "netAttachDefName": "tailscale/localnet" 
    }