apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: tailscale-oauth-eso
  namespace: tailscale
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
    name: operator-oauth
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.tailscale.key }}
