secretStore:
  name: vault-backend
  kind: ClusterSecretStore

sshpubkey:
  key: secret/data/global/sshpubkey





## Run this
# oc adm policy add-scc-to-user privileged -z csi-nfs-node-sa -n minio
# oc adm policy add-scc-to-user privileged -z csi-nfs-controller-sa -n minio


